# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Dotnet Maui Build and Test
permissions:
  contents: read

on:
  workflow_call:

jobs:
  dotnet-maui-build:
    runs-on: macos-15

    env:
      USE_WHISPER_MAUI: "TRUE"
      USE_WHISPER_MAUI_TESTS: "TRUE"

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - uses: maxim-lobanov/setup-xcode@7f352e61cbe8130c957c3bc898c4fb025784ea1e
        with:
          xcode-version: '26.1'

      - name: Download Artifacts
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: runtimes

      - name: Install dotnet workloads
        run: |
          dotnet workload install maui --ignore-failed-sources
          dotnet workload install tvos --ignore-failed-sources

      - name: Install ios simulator
        run: |
          xcodebuild -downloadPlatform iOS 

      - name: Restore dependencies
        run: dotnet restore ./Whisper.net.Maui.Tests.sln

      - name: Build ios-simulator
        run: dotnet build ./tests/Whisper.net.Tests.Maui/Whisper.net.Tests.Maui.csproj -c Debug -f net10.0-ios -r iossimulator-arm64 -p:EmbedAssembliesIntoAppBundle=true -p:CodesignKey="" -p:CodesignProvision=""

      - name: Build android
        run: dotnet build ./tests/Whisper.net.Tests.Maui/Whisper.net.Tests.Maui.csproj -c Debug -f net10.0-android -p:EmbedAssembliesIntoApk=true

      - name: Upload apk and ios app
        uses: actions/upload-artifact@v4
        with:
          name: maui-build-artifacts
          path: |
            ./tests/Whisper.net.Tests.Maui/bin/Debug/net10.0-ios/iossimulator-arm64/Whisper.net.Tests.Maui.app
            ./tests/Whisper.net.Tests.Maui/bin/Debug/net10.0-android/com.companyname.whisper.net.tests.maui-Signed.apk

  dotnet-maui-test-android:
    runs-on: ubuntu-latest
    needs: dotnet-maui-build

    env:
      USE_WHISPER_MAUI: "TRUE"

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Download Artifacts
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: maui-build-artifacts
          path: maui-build-artifacts

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install xharness
        run: dotnet tool install Microsoft.DotNet.XHarness.CLI --global --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json --version "10.0.0-*"

      - name: run android tests
        uses: reactivecircus/android-emulator-runner@62dbb605bba737720e10b196cb4220d374026a6d
        with:
          api-level: 29
          arch: x86_64
          script: xharness android test --app=./maui-build-artifacts/net10.0-android/com.companyname.whisper.net.tests.maui-Signed.apk -p com.companyname.whisper.net.tests.maui -i com.companyname.whisper.net.tests.maui.AndroidMauiTestInstrumentation -o=./test-results/android

      - name: Upload Maui Android xharness test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: xharness-android-test-results
          path: |
            ./test-results/*

  dotnet-maui-test-ios:
    runs-on: macos-15
    needs: dotnet-maui-build

    env:
      USE_WHISPER_MAUI: "TRUE"

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
        with:
          xcode-version: '26.1'
          
      - name: Install ios simulator
        run: |
          xcodebuild -downloadPlatform iOS 

      - name: Download Artifacts
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: maui-build-artifacts
          path: maui-build-artifacts

      - name: Install xharness
        run: dotnet tool install Microsoft.DotNet.XHarness.CLI --global --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json --version "10.0.0-*"

      - name: Check simulators
        run: xharness apple simulators list

      - name: run ios tests
        run: xharness apple test --app=./maui-build-artifacts/net10.0-ios/iossimulator-arm64/Whisper.net.Tests.Maui.app --output-directory=./test-results/ios --target=ios-simulator-64 --device="iPhone 16" --timeout "00:30:00"

      - name: Upload Maui iOS xharness test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: xharness-ios-test-results
          path: |
            ./test-results/*
