name: MacOs Native build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  intel-native-build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.head_ref }}

      - name: Run apple coreml build for x64
        run: make apple_coreml_x64

      - name: Run apple build for x64
        run: make apple_x64

      - name: Upload Mac Intel Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-intel-build
          path: |
            Whisper.net.Run*/*/*
            Whisper.net.Run*/*.metal
          retention-days: 7

  arm-native-build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.head_ref }}

      - name: Run apple build for arm
        run: make apple_arm

      - name: Upload Mac Arm Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-arm-build
          path: |
            Whisper.net.Run*/*/*
            Whisper.net.Run*/*.metal
          retention-days: 7
