name: MacOs Native build

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      BuildConfig:
        required: true
        type: string
        default: "Release"

jobs:
  intel-native-build:
    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Run macos build for x64
        run: |
          make apple_x64 BUILD_TYPE=${{ inputs.BuildConfig }}

      - name: Upload Mac Intel Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: mac-intel-build
          path: |
            runtimes/Whisper.net.Run*/*/*
            runtimes/Whisper.net.Run*/*.metal
          retention-days: 7

  arm-native-build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Run macos build for arm and Mac Catalyst
        run: |
          make macos_arm64 maccatalyst_arm64 BUILD_TYPE=${{ inputs.BuildConfig }}

      - name: Upload Mac Arm Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: mac-arm-build
          path: |
            runtimes/Whisper.net.Run*/*/*
            runtimes/Whisper.net.Run*/*.metal
          retention-days: 7
