# This workflow will pack all the nuget packages
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Push Nuget Packages to nuget.org

permissions:
  contents: write
  id-token: write # required for GitHub OIDC
on:
  workflow_call:

jobs:
  push-nupkgs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Download Artifacts
        id: download-artifact
        uses: actions/download-artifact@v7
        with:
          name: nupkgs
          path: nupkgs

      - name: NuGet login (OIDC â†’ temp API key)
        uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544
        id: nuget-login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push to nuget.org
        run: |
          dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }}
          dotnet nuget push ./nupkgs/*.snupkg --source https://api.nuget.org/v3/index.json --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }}

      - name: Get version from package
        id: get-version
        run: |
          version="$(ls -1 nupkgs/*.nupkg | head -n 1 | sed -E 's/.*\.([0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9]+)?)\.nupkg/\1/')"
          git config user.email "sandrohanea@users.noreply.github.com"
          git config user.name "Sandro Hanea (auto)"
          git tag -a "$version" -m "Release version $version"
          git push --tags
