# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CD (Native + dotnet)

on:
   workflow_dispatch:
      inputs:
         IsPreview:
            description: 'Is Preview'
            required: true
            type: boolean
            default: true
         PreviewSuffix:
            description: 'Preview Suffix'
            required: false
            default: 'preview'
env:
   IS_PREVIEW: ${{ inputs.IsPreview }}
   PREVIEW_SUFFIX: ${{ inputs.PreviewSuffix }}
jobs:
   android:
      uses: ./.github/workflows/android-native-build.yml

   macos:
      uses: ./.github/workflows/macos-native-build.yml

   windows:
      uses: ./.github/workflows/windows-native-build.yml
      
   windows-no-avx:
      uses: ./.github/workflows/windows-noavx-native-build.yml

   wasm:
      uses: ./.github/workflows/wasm-native-build.yml

   linux:
      uses: ./.github/workflows/linux-native-build.yml

   linux-no-avx:
      uses: ./.github/workflows/linux-noavx-native-build.yml

   windows-cuda:
      uses: ./.github/workflows/windows-cuda-native-build.yml

   windows-vulkan:
      uses: ./.github/workflows/windows-vulkan-native-build.yml

   windows-openvino:
      uses: ./.github/workflows/windows-openvino-native-build.yml
      
   linux-cuda:
      uses: ./.github/workflows/linux-cuda-native-build.yml

   linux-openvino:
      uses: ./.github/workflows/linux-openvino-native-build.yml

   macos-coreml:
      uses: ./.github/workflows/macos-coreml-native-build.yml
      
   pack-all:
      needs:
         - android
         - macos
         - windows
         - wasm
         - linux
         - windows-cuda
         - windows-vulkan
         - windows-openvino
         - linux-cuda
         - linux-openvino
         - macos-coreml
         - linux-no-avx
         - windows-no-avx
      uses: ./.github/workflows/pack-all.yml
      with:
         IsPreview: ${{ inputs.IsPreview }}
         PreviewSuffix: ${{ inputs.PreviewSuffix }}
      secrets: inherit
         
   push-nuget:
      needs:
         - pack-all
      uses: ./.github/workflows/push-all.yml
