name: Windows native build Without AVX

on:
  workflow_dispatch:
  workflow_call:

jobs:
  native-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.head_ref }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        
      - name: Run Build
        run: |
          Import-Module ./windows-scripts.ps1
          BuildWindowsBase -Arch "x64" -Configuration "Release"  -NoAvx $true
          BuildWindowsBase -Arch "x86" -Configuration "Release"  -NoAvx $true
          BuildWindowsBase -Arch "arm64" -Configuration "Release"  -NoAvx $true
        shell: pwsh

      - name: Upload Windows Vulkan Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-noavx-build
          path: "Whisper.net.Run*/win-*/*"
          retention-days: 7
